version: '3'

services:

  mongodb-dev-primary:
    image: 'bitnami/mongodb:latest'
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_data:/bitnami
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=localhost
      - MONGODB_USERNAME=user0
      - MONGODB_PASSWORD=password123
      - MONGODB_DATABASE=db1
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123Root
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_REPLICA_SET_NAME=rs1